spring:
  application:
    name: sample-provider-user
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cloudsample?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

server:
  port: 8092
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  type-aliases-package: com.cloud.sample.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
