server:
  port: 8060
spring:
  application:
    name: sample-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dzw823442238/cloudsample
          username: dzw823442238
          password: deng19921102
          search-paths: sample-config-repo
          clone-on-start: true

